server:
  port: 8085

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.finvault.notification.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.finvault.notification.dto.TransactionEvent

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply@finvault.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  topics:
    transaction-events: transaction-events

notification:
  from-email: ${MAIL_USERNAME:noreply@finvault.com}
  from-name: FinVault Banking

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.finvault: DEBUG
    org.apache.kafka: WARN
